title: "chexy-cn"
description: "车昕益的个人博客"
url: "https://chexy-cn.github.io" # 替换为你的地址
github_username: chexy-cn

# Jekyll配置
theme: minima
plugins:
  - jekyll-feed

# 自定义变量
social:
  twitter: yourhandle
